### ISSUE TITLE
Fixes for new preview UI states

### ISSUE THREAD

**Issue by jeremydw** [blinkk/editor.dev-ui#167]
1. Avoid flashing the "request failed" toast at the bottom
2. Copy changes on the buttons to "Sign in to preview server" and "Reload"
3. Opening the dialog doesn't work -- we need to substitute in the workspace variable.

![image](https://user-images.githubusercontent.com/646525/128071035-43784b2c-ccb8-45c9-bcf9-17c9582488bb.png)

**Comment by Zoramite** [comment]
fixed by e01c3ae3ae7491843ad269546c54bd60f8060538

**Comment by jeremydw** [comment]
"Failed to fetch" toast still appears at bottom. We should remove this for errors with the preview.

![image](https://user-images.githubusercontent.com/646525/128076182-e0b910e5-b728-48d9-b881-35e96eda88f3.png)
